compiler:
   solc:
       version: 0.7.6
# networks:
#   default: development
#   development:
#     ganache:
#       evm_version: istanbul
#       host: http://127.0.0.1
#       port: 8545
#       network_id: 5777

# networks:
#   development:
#     host: http://127.0.0.1
#     port: 8545
#     gas_price: auto
#     network_id: 1337

networks:
  default: development
  hardhat:
    host: http://127.0.0.1  
    port: 8545            
    gas_price: auto       
    network_id: 1337      



