from util.globaltokens import weth_usdc_pool,eth_dai_pool,btc_usdt_pool,btc_weth_pool
from enforce_typing import enforce_types
from django_app.django_app.rl_ilp_script import predict_action
predict_action()